language: node_js
node_js:
  - "5"
  - "node"
before_install:
  - cd default
  - npm install -g grunt-cli
  - npm install -g bower
install:
  - npm install
  - bower install
before_script:
  - grunt build
