language: node_js
node_js:
  - "6"
cache:
  directories:
    - default/node_modules
    - default/bower_components
before_install:
  - cd default
  - npm install -g grunt-cli
  - npm install -g bower
install:
  - npm install
  - bower install
before_script:
  - grunt build